dependencies:
  - python=3.10
  - setuptools==69.5.1
  - pip
  - pip:
      - mlflow==2.14.3
      - pandas
      - scikit-learn
      - lightgbm
      - joblib
      - numpy<2.0
      - pydantic<2
      - azureml-inference-server-http
      - azure-ai-ml
      - great_expectations==0.18.21
