name: inference-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - setuptools==68.2.2
      - wheel
      - mlflow==2.14.3
      - pandas
      - scikit-learn
      - lightgbm
      - joblib
      - numpy<2.0
      - pydantic<2
      - azureml-inference-server-http
